Simulink.defineIntEnumType( 'ModeDeclarationGroup', ...
   {'ModeDeclaration','ModeDeclaration1','ModeDeclaration2'}, ...
   [0 1 2], ...
   'DefaultValue', 'ModeDeclaration', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

